### ISSUE TITLE
File information 

### ISSUE THREAD

**Issue by JcM-productions** [gbl08ma/utilities#15]
At the File-Information-Screen it would be nice to look at the next file by pressing up and down like it is possible at the OS (System / Storage Memory / Detail [F5]).

**Comment by JcM-productions** [comment]
I had two new ideas for the file information screen:
- adding two Fkeys (F4, F5) on file information (delete, rename)
- would it be possible to go back to file information after editing a file?

**Comment by gbl08ma** [comment]
Your second suggestion has been implemented in 50054dc.

Your first suggestion can't be implemented because F4 is already taken in some situations, and F5 may be needed for other things in the future.
