### ISSUE TITLE
Key specific actions

### ISSUE THREAD

**Issue by JcM-productions** [gbl08ma/utilities#19]
Delete:
- Chronometer: Delete selected chronometers by pressing [Del].

Right/Left/Top/Bottom key:
- Calendar: Open/Close selected event by pressing right/left at the ...
    - date view
    - week view
    - search results
- Calendar: viewing any event: go to the next event on [up]/[down]
- Chronometer: Switch chronometer view by righ/left (already done I thought)
- File manager: at file information screen:
    - Open/Close file (Standart action: open/execute/view (*.jpeg)) by pressing right/left
    - go to the next file on [up]/[down]

[EXE]:
- Chronometer: Open "Set chronometer type" by pressing [EXE] at the new chronometer view.

**Comment by gbl08ma** [comment]
The remaining suggestions can't be implemented for a number of reasons:
 - Pressing the DEL key on chronometers makes it easier to clear a chronometer accidentally (twice the keys, twice the chance). A confirmation prompt could be added, but most users expect actions on the chronometer to happen immediately.
 - When viewing a calendar event or task, the up/down keys are needed for scrolling the text. It would not be too bad if it only jumped to the next/previous event when these keys are explicitly pressed (i.e. not when they are being held), but there's no practical and reliable way to detect whether the key press is "repeated" or not.
 - Setting the chronometer on EXE can't be done for key debouncing reasons (EXE would get pressed on the menu, almost immediately selecting the first option, "Upwards").

All other suggestions have been implemented or were already implemented.

**Comment by JcM-productions** [comment]
At calendar / trim database / key right:
- the "... trimming completed successfully ..." message appears but without any action

maybe you can remove pressing this key there
