### ISSUE TITLE
Same file name

### ISSUE THREAD

**Issue by JcM-productions** [gbl08ma/utilities#23]
At password generator I found out, utilities doesn't do anything on same file names.

- If you copy / cut files (same names on the new location) in the file manager, nothing happens
- Files with same names generated by the password generator resulting an "Data ERROR"

-> Would it be possible to make an extra "Overwrite / Rename / Do nothing" screen?

**Comment by gbl08ma** [comment]
I have made it show the OS default "overwrite confirmation" dialog, which doesn't allow for renaming a file (you can still refuse to overwrite, go back and rename the file, then copy/cut again). This would be useful when copying/moving files, but adding it would increase the code complexity a bit so I didn't add it; I may get back to it later.
