### ISSUE TITLE
Incorrect day of week 

### ISSUE THREAD

**Issue by Heath123** [gbl08ma/utilities#32]
![image](https://user-images.githubusercontent.com/13787163/142204899-0dd3cab7-c3ed-4e29-8e5f-49c1a69d2541.jpg)
It’s not Sunday

**Comment by Heath123** [comment]
Do you write to https://prizm.cemetech.net/index.php?title=Real-Time_Clock#RWKCNT_-_Day_of_Week_Counter?

**Comment by gbl08ma** [comment]
I'm not sure what you mean. October 17, 2021 was a Sunday. In any case, this add-in is abandonware now.

**Comment by Heath123** [comment]
> I'm not sure what you mean. October 17, 2021 was a Sunday. In any case, this add-in is abandonware now.

OH, I set the wrong month, how did I not notice that? Sorry

**Comment by Heath123** [comment]
I forgot it was November somehow
