### ISSUE TITLE
[Issue] TOTP defaults to GMT after main memory reset

### ISSUE THREAD

**Issue by POLARIS183** [gbl08ma/utilities#33]
Hi @gbl08ma ,
Whenever I reset my calculator's main / alpha memory, I often have trouble using the TOTP authenticator setting because the time zone has defaulted to UTC+0 (GMT). Have you got any ideas as to why this could be, and what I can do to fix the problem?
Thanks!

**Comment by gbl08ma** [comment]
Utilities saves settings, including the timezone, exclusively on the main memory, so this behavior is expected.
