### ISSUE TITLE
Do something about home panels

### ISSUE THREAD

**Issue by gbl08ma** [gbl08ma/utilities#8]
The left and right side of the home screen could be better used, perhaps customizable?
Ideas: balance manager balance of current wallet and last N tx, TOTP token code, password generator, display a text file...

**Comment by JcM-productions** [comment]
Maybe the other screens (top, bottom, left, right) could be used as shortcuts or gadgets / widgets for some Utilities functions.

So what functions could that be?
- these you already named,
- the file manager, calendar, CPU speed, Tasks, starting events on this day (like it is), Addin manager, ...
- I could image to have one screen as a shortlink to Run-Matrix (like "open Run-Mat on unlock")

I could imagine this extra screens like the following picture:
![extra screens](https://cloud.githubusercontent.com/assets/10922907/6106941/1a279a54-b066-11e4-9e27-bbb8906624b3.png)

You could make a list with these functions available for that, like the Utilities setup list, to assign the extra screens.

**Comment by gbl08ma** [comment]
Your idea for how it could be matches with what I was planning. The idea is to offer direct shortcuts for some things (Run-Mat, password generator, CPU speed, file manager), and information screens for others (today events, TOTP code, memory usage). The difference between the "information screens" and the "direct shortcuts" is that the information screens are not interactive. Everything would be defined from the settings screen, yes.

**Comment by JcM-productions** [comment]
If you set "Dark theme: on" and go into any extra panel (besides of Run-Mat and Memory usage, wich is extra designed as a panel I think), the border (Bdisp_Fill_VRAM it must be) of the screen is black.

If you were (same settings) in Run-Mat before (on Calc. unlock or by panel), the border of the screen is white.

I think it is because the Save_VRAM, the border is used from the screen before.

**Comment by JcM-productions** [comment]
I don't know whether it is already so, but could you make a panel for the Addin manager?

**Comment by gbl08ma** [comment]
Shortcuts to the advanced tools will only be added after all the other shortcuts and panels are added, due to the way the code is organized.

**Comment by gbl08ma** [comment]
Done in 16603bb
