### ISSUE TITLE
Fit images size

### ISSUE THREAD

**Issue by JcM-productions** [gbl08ma/utilities#9]
A function to adjust the actually image (*.jpg) to the smallest size the screen allows:
![adjust images](https://cloud.githubusercontent.com/assets/10922907/6106985/9568efec-b066-11e4-99a9-208a38f5760e.png)

**Comment by gbl08ma** [comment]
Not supported by TJpgDec, the library Utilities uses for decoding JPGs. It only allows fixed size reductions of 1/2, 1/4, 1/8, etc. (which you can use by pressing [+] and [-]) and not arbitrary zoom levels. It's not possible to support arbitrary zoom levels without more memory to hold the whole bitmap in, then scale (and even if there was enough memory, it would probably be too slow).
